version: "3.7"

services:
    application:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: app-dev
        volumes:
            - ".:/app"
        env_file:
            - docker/dev.env
        depends_on:
            - database

    # this is needed only for development,
    # because we mount the whole project directory here and
    # it shadows the static folder.
    frontend:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        volumes:
            - ".:/app"

    httpd:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: httpd
        depends_on:
            - application
        ports:
            - "8001:8000"

    database:
        restart: on-failure
        image: postgres:11-alpine
        volumes:
            - "./docker/database:/docker-entrypoint-initdb.d/"
        environment:
            POSTGRES_DB: "app"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
